config/routes.rb
Rails.application.routes.draw do
  get 'tags/:name', to: "thoughts#by_tag", as: "by_tag"
  resources :thoughts
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thought.rb
class Thought < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  validates :user_id, presence: true
  acts_as_taggable

  before_save :set_tags

  private

  def set_tags
    self.tag_list = body.scan(/#([a-zA-Z0-9]+)/).flatten.map(&:downcase)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, password_length: 8..128

  has_many :thoughts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_thought, only: [:show, :edit, :update, :destroy]
  before_action :authorized, except: [:index, :create, :new, :by_tag]

  # GET /thoughts
  # GET /thoughts.json
  def index
    @thoughts = current_user.thoughts.all
  end

  def by_tag
    @thoughts = current_user.thoughts.tagged_with(params[:name])
    render "thoughts/index"
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
  end

  # GET /thoughts/new
  def new
    @thought = current_user.thoughts.new
  end

  # GET /thoughts/1/edit
  def edit
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    @thought = current_user.thoughts.new(thought_params)

    respond_to do |format|
      if @thought.save
        format.html { redirect_to @thought, notice: 'Thought was successfully created.' }
        format.json { render :show, status: :created, location: @thought }
      else
        format.html { render :new }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thoughts/1
  # PATCH/PUT /thoughts/1.json
  def update
    respond_to do |format|
      if @thought.update(thought_params)
        format.html { redirect_to @thought, notice: 'Thought was successfully updated.' }
        format.json { render :show, status: :ok, location: @thought }
      else
        format.html { render :edit }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought.destroy
    respond_to do |format|
      format.html { redirect_to thoughts_url, notice: 'Thought was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thought
      @thought = Thought.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thought_params
      params.require(:thought).permit(:body)
    end

    def authorized
      unless current_user.id == Thought.find(params[:id]).user_id
        flash[:error] = "Not your thought"
        redirect_to thoughts_url
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
  <%= render 'layouts/nav_links_for_auth' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Openthought2" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Openthought2" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/thoughts/_form.html.erb
<%= form_with(model: thought, local: true) do |form| %>
  <% if thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
      <% thought.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thoughts/edit.html.erb
<h1>Editing Thought</h1>

<%= render 'form', thought: @thought %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

app/views/thoughts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thoughts</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thoughts.each do |thought| %>
      <tr>
        <td><%= thought.body %></td>
        <td><%= link_to 'Show', thought %></td>
        <td><%= link_to 'Edit', edit_thought_path(thought) %></td>
        <td><%= link_to 'Destroy', thought, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thought', new_thought_path %>

app/views/thoughts/new.html.erb
<h1>New Thought</h1>

<%= render 'form', thought: @thought %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @thought.body %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @thought.tag_list %>
</p>

<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>